[package]
name = "ee-tools"
version = "0.1.0"
authors = ["gabe <difioregabe@gmail.com>"]
homepage = "https://github.com/gdifiore/EE-tools"
repository = "https://github.com/gdifiore/EE-tools"
edition = "2018"

[dependencies]
clap = "2.33.1"
statrs = "0.12.0"
libmath = "0.2.1"
itertools = "0.9.0"